backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: work
    title: Work
    label: Work
    folder: "src/pages/work"
    create: true
    fields:
      - { name: company, label: Company }
      - { name: position, label: Position }
      - { name: location, label: Location }
      -   name: startDate
          label: Date started
          widget: "object"
          fields: 
          - name: startMonth
            label: Month
            widget: "number"
            valueType: "int"
            min: 1
            max: 12 
          - name: startYear
            label: Year
            widget: "number"
            valueType: "int"
            min: 1942
            max: 2030 
      -   name: endDate
          label: Date Ended
          required: false
          widget: "object"
          fields: 
          - name: endMonth
            label: Month
            widget: "number"
            valueType: "int"
            min: 1
            max: 12 
          - name: endYear
            label: Year
            widget: "number"
            valueType: "int"
            min: 1942
            max: 2030 
      - { name: summary, label: Summary, , widget: markdown }
      - { name: website, label: Website, required: false }
      - { name: logo, label: Logo, widget: "image", required: false }
      - { name: highlights, label: Highlights, widget: "list", required: false }
