backend:
  name: github
  branch: master
  repo: alexanderchabo/alexanderchabo

media_folder: static/assets
public_folder: assets

collections:
  - name: work
    label: Work
    folder: 'src/pages/work/'
    create: true
    identifier_field: position
    fields:
      - { name: category, label: Category, widget: hidden, default: work }
      - { name: position, label: Position }
      - { name: company, label: Company }
      - { name: location, label: Location }
      - { name: summary, label: Summary, widget: markdown }
      - { name: website, label: Website, required: false }
      - { name: logo, label: Logo, widget: 'image', required: true }
      - { name: highlights, label: Highlights, widget: 'list', required: false }
      - name: startDate
        label: Date startedlog
        widget: 'object'
        fields:
          - name: month
            label: Month
            widget: 'number'
            valueType: 'int'
            min: 1
            max: 12
          - name: year
            label: Year
            widget: 'number'
            valueType: 'int'
            min: 1950
            max: 2050
      - name: endDate
        label: Date Ended
        required: false
        widget: 'object'
        fields:
          - name: month
            label: Month
            widget: 'number'
            valueType: 'int'
            min: 1
            max: 12
          - name: year
            label: Year
            widget: 'number'
            valueType: 'int'
            min: 1950
            max: 2050

  - name: education
    label: Education
    folder: 'src/pages/education/'
    create: true
    identifier_field: studyType
    fields:
      - { name: category, label: Category, widget: hidden, default: education }
      - { name: institution, label: Institution }
      - { name: area, label: Area }
      - { name: studyType, label: Study Type }
      - { name: website, label: Website }
      - { name: logo, label: Logo, widget: 'image' }
      - { name: location, label: Location }
      - name: startDate
        label: Date started
        widget: 'object'
        fields:
          - name: month
            label: Month
            widget: 'number'
            valueType: 'int'
            min: 1
            max: 12
          - name: year
            label: Year
            widget: 'number'
            valueType: 'int'
            min: 1950
            max: 2050
      - name: endDate
        label: Date Ended
        required: false
        widget: 'object'
        fields:
          - name: month
            label: Month
            widget: 'number'
            valueType: 'int'
            min: 1
            max: 12
          - name: year
            label: Year
            widget: 'number'
            valueType: 'int'
            min: 1950
            max: 2050
