development:
  adapter: postgresql
  database: alexanderchabo_db_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: alexanderchabo_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: alexanderchabo_db_production
  pool: 5
  timeout: 5000
